baseURL = "https://bsachart.github.io/"
title = "My Blog"
theme = "PaperMod"

[params]
  # Many params you can customize; see PaperMod docs
  # e.g.:
  showMenu = true
  menuItems = [
    { name = "Home", url = "/" },
    { name = "About", url = "/about/" }
  ]