name: Deploy Hugo Site to GitHub Pages

# Trigger only after AI review workflow succeeds
on:
  workflow_run:
    workflows: ["AI Code Review"]
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v4

      # 2. Setup Hugo (latest)
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
          extended: true

      # 3. Build the site
      - name: Build site
        run: hugo --minify

      # 4. Upload artifact for deployment
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
